def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]

pipeline {
    agent any
    tools {
        nodejs 'node16'
        jdk 'jdk17'
    }
    environment {

        SCANNER_HOME = tool 'sonar-scanner'

        registryCredential = 'ecr:us-east-1:awscreds'
        IMAGE_NAME   = '103825649954.dkr.ecr.us-east-1.amazonaws.com/flipkartimg'               
        flipkartRegistry = "https://103825649954.dkr.ecr.us-east-1.amazonaws.com"
    }
    
    
    stages {
        stage("Clean Workspace") {
            steps {
                cleanWs()
            }
        }

        stage("Git Checkout") {
            steps {
                git branch: 'main', url: 'https://github.com/ravigfx/Flipkart-Clone-DevSecops-EKS-Scout-OWASP-ZAP-Gitops-Hard-Level-project.git'
            }
        }


 
        stage('Install Dependencies') {
            steps {
                sh "npm install"
            }
        }


        stage("Sonarqube Analysis "){
            steps{
                withSonarQubeEnv('sonar-server') {
                    sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=flipkart \
                    -Dsonar.projectKey=flipkart '''
                }
            }
        }

        stage("Quality Gate") {
            steps {
                script {
                    timeout(time: 3, unit: 'MINUTES') {
                  
                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token'
                }
            }
        }
        }


    

        stage("OWASP Dependency Check Scan") {
            steps {
                dependencyCheck additionalArguments: '''
                    --scan . 
                    --disableYarnAudit 
                    --disableNodeAudit 
                ''',
                odcInstallation: 'dp-check'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }

        // stage('Docker Scout FS') {
        //     steps {
        //         script{
        //              withCredentials([string(credentialsId: 'docker-cred', variable: 'dockerpwd')]) {
        //                 sh "docker login -u ravigfx -p ${dockerpwd}"
        //                sh 'docker-scout quickview fs://.'
        //                sh 'docker-scout cves fs://.'
        //            }
        //         }   
        //     }
        // }


            stage('Docker Scout FS') {
                steps {
                    script {
                        withCredentials([string(credentialsId: 'docker-cred', variable: 'dockerpwd')]) {
                            // Login to Docker Hub
                            sh "docker login -u ravigfx -p ${dockerpwd}"

                            // Generate a quick overview and save it as a text file
                            sh "docker-scout quickview fs://. > quickview-report.txt"

                            // Generate detailed CVE reports in JSON and text format
                            // sh "docker-scout cves fs://. --format json > cves-report.json"
                            sh "docker-scout cves fs://. > cves-report.txt"

                            // Display partial output in Jenkins console
                            sh "echo '--- Docker Scout Summary ---'"
                            sh "head -20 quickview-report.txt"
                        }
                    }
                    // Archive all generated reports for download from Jenkins UI
                    archiveArtifacts artifacts: '*.txt, *.json', fingerprint: true
                }
            }



        stage("Build Docker Image") {
            steps {
                script {

                    env.IMAGE_TAG = "ravigfx/flipkart:${BUILD_NUMBER}"
                    
                    // Optional cleanup
                    sh "docker rmi -f flipkart ${env.IMAGE_TAG} || true"

                    sh "docker build  -t flipkart ."
                }

            }
        }




    //     stage('Docker Scout Image') {
    //         steps {
    //             script{
    //                 withCredentials([string(credentialsId: 'docker-cred', variable: 'dockerpwd')]) {
    //                 sh "docker login -u ravigfx -p ${dockerpwd}"
    //                 sh 'docker-scout cves flipkart'
    //                 sh 'docker-scout recommendations flipkart'
    //             }
    //         }
    //     }
    // }


        stage('Docker Scout Image') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'docker-cred', variable: 'dockerpwd')]) {
                        // Login to Docker Hub
                        sh "docker login -u ravigfx -p ${dockerpwd}"

                        // Run Docker Scout CVE scan and save output
                        // sh "docker-scout cves flipkart --format json > image-cves-report.json"
                        sh "docker-scout cves flipkart > image-cves-report.txt"

                        // Run recommendations and save results
                        // sh "docker-scout recommendations flipkart --format json > image-recommendations.json"
                        sh "docker-scout recommendations flipkart > image-recommendations.txt"

                        // Show short summary in Jenkins console
                        // sh "echo '--- Docker Scout Image CVE Summary ---'"
                        // sh "head -20 image-cves-report.txt"
                    }
                }
                // Archive all reports for easy download
                archiveArtifacts artifacts: '*.txt, *.json', fingerprint: true
            }
        }

        


            stage("Upload App Image to ECR") {
                steps {
                    script {
                        // Tag local image for ECR
                        sh """
                            docker tag flipkart ${IMAGE_NAME}:${BUILD_NUMBER}
                            docker tag flipkart ${IMAGE_NAME}:latest
                        """

                        // Define the image object for Jenkins Docker plugin
                        def dockerImage = docker.image("${IMAGE_NAME}")

                        // Push both tags using the Jenkins ECR credentials
                        docker.withRegistry(flipkartRegistry, registryCredential) {
                            dockerImage.push("${BUILD_NUMBER}")
                            dockerImage.push("latest")
                        sh "docker logout"
                        }
                    }
                }
            }




        stage("Tag & Push to DockerHub") {
            steps {
                script {
                    withCredentials([string(credentialsId: 'docker-cred', variable: 'dockerpwd')]) {
                        sh "docker login -u ravigfx -p ${dockerpwd}"
                        sh "docker tag flipkart ${env.IMAGE_TAG}"
                        sh "docker push ${env.IMAGE_TAG}"

                        // Also push latest
                        sh "docker tag flipkart ravigfx/flipkart:latest"
                        
                        sh "docker push ravigfx/flipkart:latest"
                        sh "docker logout"
                    }
                }
            }
        }


        stage("Deploy to Container") {
            steps {
                script {
                    sh "docker rm -f flipkart || true"
                    sh "docker run -d --name flipkart -p 80:80 ${env.IMAGE_TAG}"
                }
            }
        }

        stage("DAST Scan with OWASP ZAP") {
            steps {
                script {
                    echo '🔍 Running OWASP ZAP baseline scan...'

                    // Run ZAP but ignore exit code
                    def exitCode = sh(script: '''
                        docker run --rm --user root --network host -v $(pwd):/zap/wrk:rw \
                        -t zaproxy/zap-stable zap-baseline.py \
                        -t http://localhost \
                        -r zap_report.html -J zap_report.json
                    ''', returnStatus: true)

                    echo "ZAP scan finished with exit code: ${exitCode}"

                    // Read the JSON report if it exists
                    if (fileExists('zap_report.json')) {
                        def zapJson = readJSON file: 'zap_report.json'

                        def highCount = zapJson.site.collect { site ->
                            site.alerts.findAll { it.risk == 'High' }.size()
                        }.sum()

                        def mediumCount = zapJson.site.collect { site ->
                            site.alerts.findAll { it.risk == 'Medium' }.size()
                        }.sum()

                        def lowCount = zapJson.site.collect { site ->
                            site.alerts.findAll { it.risk == 'Low' }.size()
                        }.sum()

                        echo "✅ High severity issues: ${highCount}"
                        echo "⚠️ Medium severity issues: ${mediumCount}"
                        echo "ℹ️ Low severity issues: ${lowCount}"
                    } else {
                        echo "ZAP JSON report not found, continuing build..."
                    }
                }
            }
            post {
                always {
                    echo '📦 Archiving ZAP scan reports...'
                    archiveArtifacts artifacts: 'zap_report.html,zap_report.json', allowEmptyArchive: true
                }
            }
        }


    }
    
    post {
        always {
            script {
                // 🔹 Common values
                def buildStatus = currentBuild.currentResult
                def buildUser = currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')[0]?.userId ?: 'GitHub User'
                def buildUrl = "${env.BUILD_URL}"

                // 🟢 Slack Notification
                slackSend(
                    channel: '#devsecops',
                    color: COLOR_MAP[buildStatus],
                    message: """*${buildStatus}:* Job *${env.JOB_NAME}* Build #${env.BUILD_NUMBER}
                    👤 *Started by:* ${buildUser}
                    🔗 *Build URL:* <${buildUrl}|Click Here for Details>"""
                )

                // 📧 Email Notification
            emailext (
                subject: "Pipeline ${buildStatus}: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: """
                    <p>Youtube Link :- https://www.youtube.com/@devopsravigfx </p>                                     
                    <p>Flipkart DevSecops CICD pipeline status.</p>
                    <p>Project: ${env.JOB_NAME}</p>
                    <p>Build Number: ${env.BUILD_NUMBER}</p>
                    <p>Build Status: ${buildStatus}</p>
                    <p>Started by: ${buildUser}</p>
                    <p>Build URL: <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>
                """,
                to: 'ravigfx420@gmail.com',
                from: 'ravigfx420@gmail.com',
                mimeType: 'text/html',
                attachmentsPattern: 'quickview-report.txt,cves-report.json,cves-report.txt,image-cves-report.json,image-cves-report.txt,image-recommendations.json,image-recommendations.txt,dependency-check-report.xml,zap_report.html,zap_report.json'
                    )  

            }
        }
    }

 }
